import json
import os
import sys
from pathlib import Path

def sanitize_id(s):
    if s[0].isdigit():
        return "_" + s
    return s

def emit_header(pack_path, output_path):
    print(f"Reading pack from {pack_path}...")
    with open(pack_path, 'r') as f:
        pack = json.load(f)

    # Resolve imported files
    presets = []
    base_dir = Path(r"c:\Users\hooki\Trench")
    
    for item in pack.get("entries", []):
        name = item["name"]
        shape_enum = sanitize_id(name)
        import_path = base_dir / item["source_json_path"]
        
        with open(import_path, 'r') as f:
            data = json.load(f)
            # data is {"values": {"0": 1.0, ...}, "smooth": 0, "length": 63, ...}
            
            # Convert dictionary values to sorted list
            val_dict = data["values"] # keys are strings "0", "1"...
            max_idx = data["length"] # e.g. 63
            
            val_list = [0.0] * 128
            for k, v in val_dict.items():
                idx = int(k)
                if idx < 128:
                    val_list[idx] = float(v)
            
            presets.append({
                "name": name,
                "shape_enum": shape_enum,
                "values": val_list,
                "smooth": bool(data["smooth"]),
                "length": max_idx
            })

    print(f"Emitting {len(presets)} presets to {output_path}")
    
    with open(output_path, 'w') as f:
        f.write("#pragma once\n\n")
        f.write("// AUTO-GENERATED BY tools/emit_fg_presets_header.py. DO NOT HAND-EDIT.\n\n")
        f.write("#include <juce_gui_basics/juce_gui_basics.h>\n")
        f.write("#include <array>\n\n")
        
        f.write("enum class FGShape { None, ")
        f.write(", ".join([p["shape_enum"] for p in presets]))
        f.write(", Count };\n\n")
        
        f.write("struct FGPreset {\n")
        f.write("    FGShape shape;\n")
        f.write("    const char* displayName;\n")
        f.write("    int length; // max index (e.g. 63)\n")
        f.write("    bool smooth;\n")
        f.write("    float values[128];\n")
        f.write("};\n\n")
        
        # Helper to find a preset by index
        f.write("static const FGPreset kFGPresets[] = {\n")
        for p in presets:
            f.write(f"    {{ FGShape::{p['shape_enum']}, \"{p['name']}\", {p['length']}, {str(p['smooth']).lower()}, {{ ")
            f.write(", ".join([f"{v:.6f}f" for v in p["values"]]))
            f.write(" } },\n")
        f.write("};\n\n")
        
        f.write("inline const FGPreset* getFGPreset(FGShape shape) {\n")
        f.write("    for (const auto& p : kFGPresets) if (p.shape == shape) return &p;\n")
        f.write("    return nullptr;\n")
        f.write("}\n")

if __name__ == "__main__":
    import_pack = r"c:\Users\hooki\Trench\authoring\function_packs\trench_motion_pack_v0.json"
    output_h = r"c:\Users\hooki\Trench\trench-juce\plugin\source\FunctionGeneratorPresets.h"
    emit_header(import_pack, output_h)
