"""Trench Roulette - audition-first body selector.

Three actions, visible at all times: roll, lock (per stage by clicking its
thumbnail), save. Morph is baked into the audition clip as a Lo->Hi->Lo
sweep, so you hear the motion without touching a slider.

Run:
    streamlit run tools/trench_roulette.py
"""
from __future__ import annotations

import io
import math
import random
import sys
import wave
from dataclasses import replace
from pathlib import Path

import numpy as np
import streamlit as st

_TOOLS = Path(__file__).resolve().parent
if str(_TOOLS) not in sys.path:
    sys.path.insert(0, str(_TOOLS))
_ROOT = _TOOLS.parent
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from body_dsl import Body, Slot, body_to_raw  # noqa: E402
from compile_raw import compile_raw  # noqa: E402


DIST = {
    "anchor":   {"pole": (150.0, 250.0),    "Q": (0.92, 0.96),  "gain": (0.35, 0.45)},
    "mass":     {"pole": (500.0, 1300.0),   "Q": (0.975, 0.995),"gain": (0.50, 0.62)},
    "carve":    {"pole": (1000.0, 2600.0),  "Q": (0.975, 0.997),"gain": (0.52, 0.62)},
    "pressure": {"pole": (2000.0, 3600.0),  "Q": (0.988, 0.999),"gain": (0.55, 0.62)},
    "detail":   {"pole": (3500.0, 6500.0),  "Q": (0.940, 0.990),"gain": (0.48, 0.60)},
    "boundary": {"pole": (7000.0, 11000.0), "Q": (0.940, 0.985),"gain": (0.44, 0.56)},
}
ROLES = ("anchor", "mass", "carve", "pressure", "detail", "boundary")
HOST_SR = 44100.0
SWEEP_SECONDS = 2.0


def _rand_pair(lo, hi): return random.uniform(lo, hi), random.uniform(lo, hi)

def sample_slot(role):
    d = DIST[role]
    return Slot(role=role, pole=_rand_pair(*d["pole"]), Q=_rand_pair(*d["Q"]), gain=_rand_pair(*d["gain"]))

def random_body(name="roulette"):
    return Body(name=name, boost=random.uniform(2.0, 2.8), slots=tuple(sample_slot(r) for r in ROLES), notes="trench_roulette")

def reroll(prev, locks):
    new = tuple(prev.slots[i] if locks[i] else sample_slot(prev.slots[i].role) for i in range(6))
    return replace(prev, slots=new, boost=random.uniform(2.0, 2.8))


def stage_mag(stage, freqs, sr):
    c0, c1, c2, c3, c4 = float(stage["c0"]), float(stage["c1"]), float(stage["c2"]), float(stage["c3"]), float(stage["c4"])
    w = 2.0 * np.pi * freqs / sr
    e1 = np.exp(-1j * w); e2 = np.exp(-2j * w)
    return np.abs((c0 + c1*e1 + c2*e2) / (1.0 + c3*e1 + c4*e2))


def coefs_at(cart, morph):
    keyframes = {kf["label"]: kf for kf in cart["keyframes"]}
    lo, hi = keyframes["M0_Q0"]["stages"], keyframes["M100_Q0"]["stages"]
    return [tuple(float(a[k])*(1-morph) + float(b[k])*morph for k in ("c0","c1","c2","c3","c4")) for a,b in zip(lo, hi)]


def filter_block(x, coefs_list, boost):
    y = x * boost
    for coefs in coefs_list:
        c0, c1, c2, c3, c4 = coefs
        if (c0, c1, c2, c3, c4) == (1.0, 0.0, 0.0, 0.0, 0.0):
            continue
        out = np.zeros_like(y)
        xn1 = xn2 = yn1 = yn2 = 0.0
        for n in range(len(y)):
            xn = y[n]
            yn = c0*xn + c1*xn1 + c2*xn2 - c3*yn1 - c4*yn2
            out[n] = yn
            xn2, xn1 = xn1, xn
            yn2, yn1 = yn1, yn
        y = out
    return y


def render_sweep(cart, boost, seed):
    """Render a Lo->Hi->Lo morph sweep through the cascade (5 snapshots)."""
    n_total = int(HOST_SR * SWEEP_SECONDS)
    snapshots = 5
    block = n_total // snapshots
    rng = np.random.default_rng(seed)
    out = np.zeros(n_total)
    # Triangle wave: 0 -> 1 -> 0 in 5 steps → 0.0, 0.5, 1.0, 0.5, 0.0
    morphs = [0.0, 0.5, 1.0, 0.5, 0.0]
    for i, m in enumerate(morphs):
        start = i * block
        end = (i + 1) * block if i < snapshots - 1 else n_total
        sig = rng.standard_normal(end - start).astype(np.float64) * 0.1
        out[start:end] = filter_block(sig, coefs_at(cart, m), boost)
    return out


def make_wav(samples, sr):
    peak = float(np.max(np.abs(samples))) or 1.0
    norm = (samples / peak * 0.85 * 32767.0).astype(np.int16)
    buf = io.BytesIO()
    with wave.open(buf, "wb") as wf:
        wf.setnchannels(1); wf.setsampwidth(2); wf.setframerate(int(sr))
        wf.writeframes(norm.tobytes())
    return buf.getvalue()


def body_to_py_source(body):
    def pair(v):
        if isinstance(v, (tuple, list)):
            return float(v[0]), float(v[1])
        return float(v), float(v)
    lines = [
        '"""Generated by tools/trench_roulette."""',
        "from tools.body_dsl import Body, Slot",
        "",
        "BODY = Body(",
        f'    name="{body.name}",',
        f"    boost={body.boost:.3f},",
        f'    notes="{body.notes}",',
        "    slots=(",
    ]
    for s in body.slots:
        pl, ph = pair(s.pole); ql, qh = pair(s.Q); gl, gh = pair(s.gain)
        lines.append(f'        Slot("{s.role}", pole=({pl:.1f}, {ph:.1f}), Q=({ql:.4f}, {qh:.4f}), gain=({gl:.3f}, {gh:.3f})),')
    lines += ["    ),", ")", ""]
    return "\n".join(lines)


def save_body_py(body, out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / f"{body.name}.py"
    path.write_text(body_to_py_source(body), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# UI
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Trench Roulette", layout="wide", initial_sidebar_state="collapsed")
st.markdown("""
<style>
.block-container {padding-top: 1.2rem; padding-bottom: 1rem; max-width: 1200px;}
div[data-testid="stButton"] > button {width: 100%; border-radius: 6px;}
div[data-testid="stHorizontalBlock"] {align-items: center;}
[data-testid="stImage"] img {border-radius: 8px;}
.tile-locked img {outline: 3px solid #ef4444 !important; outline-offset: -3px;}
</style>
""", unsafe_allow_html=True)

if "body" not in st.session_state:
    st.session_state.body = random_body()
if "locks" not in st.session_state:
    st.session_state.locks = [False] * 6
if "roll_count" not in st.session_state:
    st.session_state.roll_count = 0
if "show_detail" not in st.session_state:
    st.session_state.show_detail = False
if "saved_msg" not in st.session_state:
    st.session_state.saved_msg = ""

# Header: body name, roll count, primary actions
h1, h2, h3 = st.columns([3, 1, 1])
h1.markdown(f"### {st.session_state.body.name} · roll #{st.session_state.roll_count}")
if h2.button("roll", type="primary"):
    st.session_state.body = reroll(st.session_state.body, st.session_state.locks)
    st.session_state.roll_count += 1
    st.session_state.saved_msg = ""
    st.rerun()
st.session_state.show_detail = h3.toggle("detail", value=st.session_state.show_detail)

body = st.session_state.body
raw = body_to_raw(body)
cart = compile_raw(raw)

# Thumbnails + lock toggles
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

F_MIN, F_MAX, NPTS = 40.0, 20000.0, 512
freqs = np.logspace(math.log10(F_MIN), math.log10(F_MAX), NPTS)
kfs = {kf["label"]: kf for kf in cart["keyframes"]}
lo_stages = kfs["M0_Q0"]["stages"]
hi_stages = kfs["M100_Q0"]["stages"]

def make_thumb(stage_lo, stage_hi, locked):
    fig, ax = plt.subplots(figsize=(2.0, 1.4), dpi=110, facecolor="#0b1020")
    lo_db = 20.0 * np.log10(np.maximum(stage_mag(stage_lo, freqs, HOST_SR), 1e-12))
    hi_db = 20.0 * np.log10(np.maximum(stage_mag(stage_hi, freqs, HOST_SR), 1e-12))
    ax.fill_between(freqs, lo_db, -60, color="#7dd3fc", alpha=0.15)
    ax.fill_between(freqs, hi_db, -60, color="#86efac", alpha=0.15)
    ax.plot(freqs, lo_db, color="#7dd3fc", linewidth=1.4)
    ax.plot(freqs, hi_db, color="#86efac", linewidth=1.4)
    ax.set_xscale("log"); ax.set_xlim(F_MIN, F_MAX); ax.set_ylim(-40, 45)
    ax.set_facecolor("#0b1020")
    ax.set_xticks([]); ax.set_yticks([])
    for sp in ax.spines.values():
        sp.set_color("#ef4444" if locked else "#1e293b")
        sp.set_linewidth(2.2 if locked else 1.0)
    fig.tight_layout(pad=0.1)
    buf = io.BytesIO()
    fig.savefig(buf, format="png", facecolor="#0b1020", dpi=110, bbox_inches="tight", pad_inches=0.05)
    plt.close(fig)
    buf.seek(0)
    return buf.read()

st.markdown("##### click a tile to lock/unlock it")
tile_cols = st.columns(6)
for i in range(6):
    with tile_cols[i]:
        img_bytes = make_thumb(lo_stages[i], hi_stages[i], st.session_state.locks[i])
        st.image(img_bytes, use_container_width=True)
        label = "🔒 locked" if st.session_state.locks[i] else "lock"
        if st.button(label, key=f"lk_{i}", type=("secondary" if not st.session_state.locks[i] else "primary")):
            st.session_state.locks[i] = not st.session_state.locks[i]
            st.rerun()

# Audition
st.markdown("##### audition — morph sweep Lo → Hi → Lo")
sweep = render_sweep(cart, body.boost, st.session_state.roll_count * 17 + 42)
st.audio(make_wav(sweep, HOST_SR), format="audio/wav")

# Save
st.markdown("---")
sv1, sv2, sv3 = st.columns([3, 2, 1])
name = sv1.text_input("name", value=body.name, label_visibility="collapsed", placeholder="body name")
if sv2.button("💾 save to authoring/bodies/"):
    out_body = replace(body, name=name)
    path = save_body_py(out_body, _ROOT / "authoring" / "bodies")
    st.session_state.saved_msg = f"saved → {path.name}"
if st.session_state.saved_msg:
    sv3.success(st.session_state.saved_msg)

# Detail panel (hidden by default)
if st.session_state.show_detail:
    st.markdown("---")
    st.markdown("##### detail — cascade response (mid-morph)")
    coefs_mid = coefs_at(cart, 0.5)
    mag = np.ones_like(freqs) * body.boost
    for c in coefs_mid:
        if c == (1.0, 0.0, 0.0, 0.0, 0.0):
            continue
        mag = mag * stage_mag({"c0": c[0], "c1": c[1], "c2": c[2], "c3": c[3], "c4": c[4]}, freqs, HOST_SR)
    mag_db = 20.0 * np.log10(np.maximum(mag, 1e-12))
    fig_d, ax_d = plt.subplots(figsize=(10.5, 3.5), dpi=120, facecolor="#0b1020")
    ax_d.plot(freqs, mag_db, color="#7dd3fc", linewidth=1.6)
    ax_d.set_xscale("log"); ax_d.set_xlim(F_MIN, F_MAX)
    ax_d.set_facecolor("#0b1020")
    ax_d.grid(True, which="both", color="#1e293b", linewidth=0.3, alpha=0.7)
    ax_d.tick_params(colors="#64748b", labelsize=8)
    for sp in ax_d.spines.values():
        sp.set_color("#1e293b")
    ax_d.set_xlabel("Hz", color="#64748b"); ax_d.set_ylabel("dB", color="#64748b")
    fig_d.tight_layout()
    st.pyplot(fig_d, clear_figure=True)
    st.caption("role assignments: " + " · ".join(f"{i+1}={s.role}" for i, s in enumerate(body.slots)))
