pub mod agc;
pub mod auto_sequencer;
pub mod cartridge;
pub mod cascade;
pub mod cluster;
pub mod engine;
pub mod function_generator;
pub mod hedz_golden;
pub mod hedz_rom;
pub mod heritage_objects;
pub mod desk_drive;
pub mod motor;
pub mod pole_block;
pub mod qsound_spatial;
pub mod resampler;
pub mod role;

pub use agc::agc_step;
pub use cartridge::{Cartridge, CornerData, NUM_COEFFS, NUM_STAGES};
pub use cascade::{Cascade, BLOCK_SIZE, TOTAL_STAGES};
pub use cluster::{Cluster, ClusterPlan, ClusterStage, InterferenceLink, StageFunction};
pub use engine::{DebugToggles, FilterEngine};
pub use heritage_objects::{HeritageDesignerTemplate, HeritageObject, HeritageSamplePoint};
pub use desk_drive::DeskDrive;
pub use motor::{ForceCurve, Motor, MotorId};
pub use pole_block::{compile_pole_bank, ComplexPole, PoleBankError, PoleBlock, PoleBlockError};
pub use role::Role;
